/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIEstudiante;

import UIAdmin.*;
import UIAdmin.ABC_Curso.AgregarCurso;
import UIAdmin.ABC_Curso.EditarCurso;
import UIAdmin.ABC_Edificio.AgregarEdificio;
import UIAdmin.ABC_Edificio.EliminarEdificio;
import UIAdmin.ABC_Salon.AgregarSalon;
import UIAdmin.ABC_Salon.EditarSalon;
import UIAdmin.ABC_Salon.VisualizarCursos;
import UIAdmin.ABC_Usuario.AgregarUsuario;
import UIAdmin.ABC_Usuario.EditarUsuario;
import UIGeneral.Login;
import implementacion.EstructuraGeneral;
import java.awt.Image;
import javax.swing.ImageIcon;



/**
 *
 * @author erikssonherlo
 */
public class InicioEstudiante extends javax.swing.JFrame {

    public InicioEstudiante() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.pack();
        datoUsuario.setText(String.valueOf(EstructuraGeneral.getUsuarioActual().getId()));
        datoNombre.setText(EstructuraGeneral.getUsuarioActual().getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        ABCUsuarios2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        instruccionesUsuario2 = new javax.swing.JLabel();
        instruccionesUsuario3 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        datoUsuario = new javax.swing.JLabel();
        datoNombre = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        ABCSalones = new javax.swing.JButton();
        titulo3 = new javax.swing.JLabel();
        cargarDatos = new javax.swing.JButton();
        ABCUsuarios3 = new javax.swing.JButton();
        ABCUsuarios = new javax.swing.JButton();
        ABCSalones1 = new javax.swing.JButton();
        ABCSalones2 = new javax.swing.JButton();
        titulo4 = new javax.swing.JLabel();
        ABCCursos2 = new javax.swing.JButton();
        ABCCursos3 = new javax.swing.JButton();
        titulo5 = new javax.swing.JLabel();
        ABCEdificios1 = new javax.swing.JButton();
        ABCEdificios2 = new javax.swing.JButton();
        ABCCursos4 = new javax.swing.JButton();
        ABCCursos1 = new javax.swing.JButton();
        titulo6 = new javax.swing.JLabel();
        instruccionesUsuario4 = new javax.swing.JLabel();
        instruccionesUsuario5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoMini.png"))); // NOI18N
        logo.setText("Logo");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, -1));

        titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo.setForeground(new java.awt.Color(1, 1, 1));
        titulo.setText("USUARIOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, 40));

        ABCUsuarios2.setBackground(new java.awt.Color(43, 46, 46));
        ABCUsuarios2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCUsuarios2.setForeground(new java.awt.Color(250, 250, 244));
        ABCUsuarios2.setText("MODIFICAR USUARIOS");
        ABCUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCUsuarios2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCUsuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, 40));

        salir.setBackground(new java.awt.Color(43, 46, 46));
        salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(250, 250, 244));
        salir.setText("CERRAR SESION");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 140, 40));

        instruccionesUsuario2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario2.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario2.setText("Usuario:");
        getContentPane().add(instruccionesUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 100, 30));

        instruccionesUsuario3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        instruccionesUsuario3.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario3.setText("de la Facultad de Ingeniería");
        getContentPane().add(instruccionesUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 370, 50));

        titulo1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        titulo1.setForeground(new java.awt.Color(1, 1, 1));
        titulo1.setText("SISTEMA DE ASIGNACIONES USAC");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 880, 53));

        datoUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        datoUsuario.setForeground(new java.awt.Color(4, 2, 2));
        datoUsuario.setText("Usuario");
        getContentPane().add(datoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 290, 30));

        datoNombre.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        datoNombre.setForeground(new java.awt.Color(4, 2, 2));
        datoNombre.setText("Nombre");
        getContentPane().add(datoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 290, 30));

        titulo2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo2.setForeground(new java.awt.Color(1, 1, 1));
        titulo2.setText("SALONES");
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 260, 40));

        ABCSalones.setBackground(new java.awt.Color(43, 46, 46));
        ABCSalones.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCSalones.setForeground(new java.awt.Color(250, 250, 244));
        ABCSalones.setText("AGREGAR SALONES");
        ABCSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCSalonesActionPerformed(evt);
            }
        });
        getContentPane().add(ABCSalones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 290, 40));

        titulo3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo3.setForeground(new java.awt.Color(1, 1, 1));
        titulo3.setText("BIENVENIDO");
        getContentPane().add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, 310, 40));

        cargarDatos.setBackground(new java.awt.Color(43, 46, 46));
        cargarDatos.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cargarDatos.setForeground(new java.awt.Color(250, 250, 244));
        cargarDatos.setText("CARGAR DATOS");
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(cargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 290, 40));

        ABCUsuarios3.setBackground(new java.awt.Color(43, 46, 46));
        ABCUsuarios3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCUsuarios3.setForeground(new java.awt.Color(250, 250, 244));
        ABCUsuarios3.setText("ELIMINAR USUARIOS");
        ABCUsuarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCUsuarios3ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 290, 40));

        ABCUsuarios.setBackground(new java.awt.Color(43, 46, 46));
        ABCUsuarios.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCUsuarios.setForeground(new java.awt.Color(250, 250, 244));
        ABCUsuarios.setText("AGREGAR USUARIOS");
        ABCUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(ABCUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, 40));

        ABCSalones1.setBackground(new java.awt.Color(43, 46, 46));
        ABCSalones1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCSalones1.setForeground(new java.awt.Color(250, 250, 244));
        ABCSalones1.setText("MODIFICAR SALONES");
        ABCSalones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCSalones1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCSalones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 290, 40));

        ABCSalones2.setBackground(new java.awt.Color(43, 46, 46));
        ABCSalones2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCSalones2.setForeground(new java.awt.Color(250, 250, 244));
        ABCSalones2.setText("ELIMINAR SALONES");
        ABCSalones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCSalones2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCSalones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 290, 40));

        titulo4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo4.setForeground(new java.awt.Color(1, 1, 1));
        titulo4.setText("CURSOS");
        getContentPane().add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 200, 40));

        ABCCursos2.setBackground(new java.awt.Color(43, 46, 46));
        ABCCursos2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCCursos2.setForeground(new java.awt.Color(250, 250, 244));
        ABCCursos2.setText("MODIFICAR CURSOS");
        ABCCursos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCCursos2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCCursos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 290, 40));

        ABCCursos3.setBackground(new java.awt.Color(43, 46, 46));
        ABCCursos3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCCursos3.setForeground(new java.awt.Color(250, 250, 244));
        ABCCursos3.setText("VISUALIZAR CURSOS");
        ABCCursos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCCursos3ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCCursos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 290, 40));

        titulo5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo5.setForeground(new java.awt.Color(1, 1, 1));
        titulo5.setText("EDIFICIOS");
        getContentPane().add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 250, 40));

        ABCEdificios1.setBackground(new java.awt.Color(43, 46, 46));
        ABCEdificios1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCEdificios1.setForeground(new java.awt.Color(250, 250, 244));
        ABCEdificios1.setText("AGREGAR EDIFICIOS");
        ABCEdificios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCEdificios1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCEdificios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 290, 40));

        ABCEdificios2.setBackground(new java.awt.Color(43, 46, 46));
        ABCEdificios2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCEdificios2.setForeground(new java.awt.Color(250, 250, 244));
        ABCEdificios2.setText("ELIMINAR EDIFICIOS");
        ABCEdificios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCEdificios2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCEdificios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 290, 40));

        ABCCursos4.setBackground(new java.awt.Color(43, 46, 46));
        ABCCursos4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCCursos4.setForeground(new java.awt.Color(250, 250, 244));
        ABCCursos4.setText("ELIMINAR CURSOS");
        ABCCursos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCCursos4ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCCursos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 290, 40));

        ABCCursos1.setBackground(new java.awt.Color(43, 46, 46));
        ABCCursos1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABCCursos1.setForeground(new java.awt.Color(250, 250, 244));
        ABCCursos1.setText("AGREGAR CURSOS");
        ABCCursos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABCCursos1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABCCursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 290, 40));

        titulo6.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo6.setForeground(new java.awt.Color(1, 1, 1));
        titulo6.setText("ADMINISTRACION");
        getContentPane().add(titulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 430, 40));

        instruccionesUsuario4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario4.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario4.setText("Nombre:");
        getContentPane().add(instruccionesUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 120, 30));

        instruccionesUsuario5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        instruccionesUsuario5.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario5.setText("Sistema de Asignación de Cursos");
        getContentPane().add(instruccionesUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 410, 50));

        fondo.setBackground(new java.awt.Color(59, 55, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.jpg"))); // NOI18N
        fondo.setText("Fondo General");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioEstudiante().setVisible(true);
            }
        });
    }
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        EstructuraGeneral.cerrarSesion();
        this.dispose();
        new Login();
    }//GEN-LAST:event_salirActionPerformed

    private void ABCUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCUsuarios2ActionPerformed
        new EditarUsuario();
        
    }//GEN-LAST:event_ABCUsuarios2ActionPerformed

    private void ABCSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCSalonesActionPerformed
        new AgregarSalon();
    }//GEN-LAST:event_ABCSalonesActionPerformed

    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
        new CargarDatos();        // TODO add your handling code here:
    }//GEN-LAST:event_cargarDatosActionPerformed

    private void ABCUsuarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCUsuarios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABCUsuarios3ActionPerformed

    private void ABCUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCUsuariosActionPerformed
        // TODO add your handling code here:
        new AgregarUsuario();
    }//GEN-LAST:event_ABCUsuariosActionPerformed

    private void ABCSalones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCSalones1ActionPerformed
        new EditarSalon();
    }//GEN-LAST:event_ABCSalones1ActionPerformed

    private void ABCSalones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCSalones2ActionPerformed
       new EditarSalon();
    }//GEN-LAST:event_ABCSalones2ActionPerformed

    private void ABCCursos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCCursos2ActionPerformed
    new EditarCurso();        // TODO add your handling code here:
    }//GEN-LAST:event_ABCCursos2ActionPerformed

    private void ABCCursos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCCursos3ActionPerformed
    new VisualizarCursos();        // TODO add your handling code here:
    }//GEN-LAST:event_ABCCursos3ActionPerformed

    private void ABCEdificios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCEdificios1ActionPerformed
        new AgregarEdificio();
    }//GEN-LAST:event_ABCEdificios1ActionPerformed

    private void ABCEdificios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCEdificios2ActionPerformed
        new EliminarEdificio();
    }//GEN-LAST:event_ABCEdificios2ActionPerformed

    private void ABCCursos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCCursos4ActionPerformed
    new EditarCurso();        // TODO add your handling code here:
    }//GEN-LAST:event_ABCCursos4ActionPerformed

    private void ABCCursos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABCCursos1ActionPerformed
        new AgregarCurso();
    }//GEN-LAST:event_ABCCursos1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ABCCursos1;
    public javax.swing.JButton ABCCursos2;
    public javax.swing.JButton ABCCursos3;
    public javax.swing.JButton ABCCursos4;
    public javax.swing.JButton ABCEdificios1;
    public javax.swing.JButton ABCEdificios2;
    public javax.swing.JButton ABCSalones;
    public javax.swing.JButton ABCSalones1;
    public javax.swing.JButton ABCSalones2;
    public javax.swing.JButton ABCUsuarios;
    public javax.swing.JButton ABCUsuarios2;
    public javax.swing.JButton ABCUsuarios3;
    public javax.swing.JButton cargarDatos;
    public javax.swing.JLabel datoNombre;
    public javax.swing.JLabel datoUsuario;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel instruccionesUsuario2;
    public javax.swing.JLabel instruccionesUsuario3;
    public javax.swing.JLabel instruccionesUsuario4;
    public javax.swing.JLabel instruccionesUsuario5;
    public javax.swing.JLabel logo;
    public javax.swing.JButton salir;
    public javax.swing.JLabel titulo;
    public javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public javax.swing.JLabel titulo3;
    public javax.swing.JLabel titulo4;
    public javax.swing.JLabel titulo5;
    public javax.swing.JLabel titulo6;
    // End of variables declaration//GEN-END:variables
}
