/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIAdmin;

import UIAdmin.ABC_Curso.*;
import UIAdmin.ABC_Usuario.*;
import UIAdmin.ABC_Edificio.*;
import gramatica.Lexer;
import gramatica.Parser;
import implementacion.CargaArchivo;
import implementacion.EstructuraGeneral;
import java.awt.Image;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import objetos.Estudiante;
import objetos.Usuario;

/**
 *
 * @author erikssonherlo
 */
public class CargarDatos extends javax.swing.JFrame {

    private String cadena;

    /**
     * Creates new form Interfaz
     */
    public CargarDatos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        cargarArchivo = new javax.swing.JButton();
        nombreArchivo = new javax.swing.JLabel();
        instruccionesUsuario2 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoMini.png"))); // NOI18N
        logo.setText("Logo");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 130));

        titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 40)); // NOI18N
        titulo.setForeground(new java.awt.Color(1, 1, 1));
        titulo.setText("CARGAR DATOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 340, 53));

        cargarArchivo.setBackground(new java.awt.Color(43, 46, 46));
        cargarArchivo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        cargarArchivo.setForeground(new java.awt.Color(250, 250, 244));
        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, 40));

        nombreArchivo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        nombreArchivo.setForeground(new java.awt.Color(4, 2, 2));
        nombreArchivo.setText("Nombre del Archivo");
        getContentPane().add(nombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 270, 40));

        instruccionesUsuario2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario2.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario2.setText("Cargar los Datos por medio de un Archivo de Entrada:");
        getContentPane().add(instruccionesUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 510, 30));

        regresar.setBackground(new java.awt.Color(43, 46, 46));
        regresar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        regresar.setForeground(new java.awt.Color(250, 250, 244));
        regresar.setText("Regresar al Menú");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 210, 40));

        fondo.setBackground(new java.awt.Color(59, 55, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.jpg"))); // NOI18N
        fondo.setText("Fondo General");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarDatos().setVisible(true);
            }
        });
    }
    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed

        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fc.getSelectedFile();
            nombreArchivo.setText(archivo.getName());

            try (FileReader fr = new FileReader(archivo)) {
                cadena = "";
                int valor = fr.read();
                while (valor != -1) {
                    cadena = cadena + (char) valor;
                    valor = fr.read();
                }
                System.out.println(cadena);

            } catch (IOException ex) {
                System.out.println("Error al obtener archivo");
            }
        }

        try {
            StringReader reader = new StringReader(cadena);
            Lexer lexer = new Lexer(reader);
            Parser parser = new Parser(lexer);
            parser.parse();

            JOptionPane.showMessageDialog(this, "Se han cargado los datos correctamente.");
            CargaArchivo cargaDatos = new CargaArchivo(
                    parser.getListaEstudiantes(),
                    parser.getListaUsuarios(),
                    parser.getListaCatedraticos(),
                    parser.getListaEdificios(),
                    parser.getListaSalones(),
                    parser.getListaCursos(),
                    parser.getListaHorarios(),
                    parser.getListaAsignaciones()
            );
            cargaDatos.cargarDatos();
        } catch (Exception ex) {
            Logger.getLogger(CargarDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cargarArchivo;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel instruccionesUsuario2;
    public javax.swing.JLabel logo;
    public javax.swing.JLabel nombreArchivo;
    public javax.swing.JButton regresar;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
