/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIColaborador;

import UIAdmin.*;
import UIAdmin.ABC_Curso.AgregarCurso;
import UIAdmin.ABC_Curso.EditarCurso;
import UIAdmin.ABC_Edificio.AgregarEdificio;
import UIAdmin.ABC_Edificio.EliminarEdificio;
import UIAdmin.ABC_Salon.AgregarSalon;
import UIAdmin.ABC_Salon.EditarSalon;
import UIAdmin.ABC_Salon.VisualizarCursos;
import UIAdmin.ABC_Usuario.AgregarUsuario;
import UIAdmin.ABC_Usuario.EditarUsuario;
import UIColaborador.ABC_Catedratico.AgregarCatedratico;
import UIColaborador.ABC_Catedratico.EditarCatedratico;
import UIColaborador.ABC_Catedratico.VisualizarCatedraticos;
import UIColaborador.ABC_Estudiante.AgregarEstudiante;
import UIColaborador.ABC_Estudiante.EditarEstudiante;
import UIColaborador.ABC_Estudiante.VisualizarEstudiante;
import UIGeneral.Login;
import implementacion.EstructuraGeneral;
import java.awt.Image;
import javax.swing.ImageIcon;



/**
 *
 * @author erikssonherlo
 */
public class InicioColaborador extends javax.swing.JFrame {

    public InicioColaborador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.pack();
        datoUsuario.setText(String.valueOf(EstructuraGeneral.getUsuarioActual().getId()));
        datoNombre.setText(EstructuraGeneral.getUsuarioActual().getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instruccionesUsuario2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        datoUsuario = new javax.swing.JLabel();
        datoNombre = new javax.swing.JLabel();
        titulo5 = new javax.swing.JLabel();
        instruccionesUsuario4 = new javax.swing.JLabel();
        instruccionesUsuario5 = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        titulo7 = new javax.swing.JLabel();
        ABC_Estudiantes1 = new javax.swing.JButton();
        ABC_Estudiantes2 = new javax.swing.JButton();
        ABC_Estudiantes3 = new javax.swing.JButton();
        ABC_Estudiantes4 = new javax.swing.JButton();
        titulo6 = new javax.swing.JLabel();
        ABC_Catedraticos1 = new javax.swing.JButton();
        ABC_Catedraticos2 = new javax.swing.JButton();
        ABC_Catedraticos3 = new javax.swing.JButton();
        ABC_Catedraticos4 = new javax.swing.JButton();
        titulo2 = new javax.swing.JLabel();
        ABC_Cursos1 = new javax.swing.JButton();
        ABC_Cursos2 = new javax.swing.JButton();
        ABC_Cursos3 = new javax.swing.JButton();
        ABC_Cursos4 = new javax.swing.JButton();
        titulo3 = new javax.swing.JLabel();
        ABC_Salones1 = new javax.swing.JButton();
        ABC_Salones2 = new javax.swing.JButton();
        ABC_Salones3 = new javax.swing.JButton();
        titulo4 = new javax.swing.JLabel();
        ABC_Asignaciones = new javax.swing.JButton();
        ABC_Edificios2 = new javax.swing.JButton();
        ABC_Edificios1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoMini.png"))); // NOI18N
        logo.setText("Logo");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, -1));

        titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo.setForeground(new java.awt.Color(1, 1, 1));
        titulo.setText("ESTUDIANTES");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 340, 40));

        instruccionesUsuario2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario2.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario2.setText("Usuario:");
        getContentPane().add(instruccionesUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 100, 30));

        titulo1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        titulo1.setForeground(new java.awt.Color(1, 1, 1));
        titulo1.setText("SISTEMA DE ASIGNACIONES USAC");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 880, 53));

        datoUsuario.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        datoUsuario.setForeground(new java.awt.Color(4, 2, 2));
        datoUsuario.setText("Usuario");
        getContentPane().add(datoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 290, 30));

        datoNombre.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        datoNombre.setForeground(new java.awt.Color(4, 2, 2));
        datoNombre.setText("Nombre");
        getContentPane().add(datoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 290, 30));

        titulo5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo5.setForeground(new java.awt.Color(1, 1, 1));
        titulo5.setText("ASIGNACIONES");
        getContentPane().add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 370, 40));

        instruccionesUsuario4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        instruccionesUsuario4.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario4.setText("Nombre:");
        getContentPane().add(instruccionesUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 120, 30));

        instruccionesUsuario5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        instruccionesUsuario5.setForeground(new java.awt.Color(4, 2, 2));
        instruccionesUsuario5.setText("Sistema de Asignación de Cursos de la Facultad de Ingeniería");
        getContentPane().add(instruccionesUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 760, 40));

        cerrarSesion.setBackground(new java.awt.Color(43, 46, 46));
        cerrarSesion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 12)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(250, 250, 244));
        cerrarSesion.setText("CERRAR SESION");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 140, 40));

        titulo7.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo7.setForeground(new java.awt.Color(1, 1, 1));
        titulo7.setText("SALONES");
        getContentPane().add(titulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 220, 40));

        ABC_Estudiantes1.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Estudiantes1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Estudiantes1.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Estudiantes1.setText("AGREGAR ESTUDIANTES");
        ABC_Estudiantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Estudiantes1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Estudiantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 290, 40));

        ABC_Estudiantes2.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Estudiantes2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Estudiantes2.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Estudiantes2.setText("MODIFICAR ESTUDIANTES");
        ABC_Estudiantes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Estudiantes2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Estudiantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 290, 40));

        ABC_Estudiantes3.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Estudiantes3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Estudiantes3.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Estudiantes3.setText("VISUALIZAR ESTUDIANTES");
        ABC_Estudiantes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Estudiantes3ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Estudiantes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 40));

        ABC_Estudiantes4.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Estudiantes4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Estudiantes4.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Estudiantes4.setText("ELIMINAR CURSOS");
        ABC_Estudiantes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Estudiantes4ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Estudiantes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 290, 40));

        titulo6.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo6.setForeground(new java.awt.Color(1, 1, 1));
        titulo6.setText("EDIFICIOS");
        getContentPane().add(titulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 250, 40));

        ABC_Catedraticos1.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Catedraticos1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Catedraticos1.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Catedraticos1.setText("AGREGAR CATEDRATICOS");
        ABC_Catedraticos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Catedraticos1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Catedraticos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 290, 40));

        ABC_Catedraticos2.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Catedraticos2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Catedraticos2.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Catedraticos2.setText("MODIFICAR CATEDRATICOS");
        ABC_Catedraticos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Catedraticos2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Catedraticos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 290, 40));

        ABC_Catedraticos3.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Catedraticos3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Catedraticos3.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Catedraticos3.setText("VISUALIZAR CATEDRATICOS");
        ABC_Catedraticos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Catedraticos3ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Catedraticos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 290, 40));

        ABC_Catedraticos4.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Catedraticos4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Catedraticos4.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Catedraticos4.setText("ELIMINAR CATEDRATICOS");
        ABC_Catedraticos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Catedraticos4ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Catedraticos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 290, 40));

        titulo2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo2.setForeground(new java.awt.Color(1, 1, 1));
        titulo2.setText("CATEDRATICOS");
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 370, 40));

        ABC_Cursos1.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Cursos1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Cursos1.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Cursos1.setText("AGREGAR CURSOS");
        ABC_Cursos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Cursos1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Cursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 290, 40));

        ABC_Cursos2.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Cursos2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Cursos2.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Cursos2.setText("MODIFICAR CURSOS");
        ABC_Cursos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Cursos2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Cursos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 290, 290, 40));

        ABC_Cursos3.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Cursos3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Cursos3.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Cursos3.setText("VISUALIZAR CURSOS");
        ABC_Cursos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Cursos3ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Cursos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 290, 40));

        ABC_Cursos4.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Cursos4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Cursos4.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Cursos4.setText("ELIMINAR CURSOS");
        ABC_Cursos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Cursos4ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Cursos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 290, 40));

        titulo3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo3.setForeground(new java.awt.Color(1, 1, 1));
        titulo3.setText("BIENVENIDO");
        getContentPane().add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 310, 40));

        ABC_Salones1.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Salones1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Salones1.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Salones1.setText("AGREGAR SALONES");
        ABC_Salones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Salones1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Salones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 290, 40));

        ABC_Salones2.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Salones2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Salones2.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Salones2.setText("MODIFICAR SALONES");
        ABC_Salones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Salones2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Salones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 290, 40));

        ABC_Salones3.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Salones3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Salones3.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Salones3.setText("ELIMINAR SALONES");
        ABC_Salones3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Salones3ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Salones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 780, 290, 40));

        titulo4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 44)); // NOI18N
        titulo4.setForeground(new java.awt.Color(1, 1, 1));
        titulo4.setText("CURSOS");
        getContentPane().add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 200, 40));

        ABC_Asignaciones.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Asignaciones.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Asignaciones.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Asignaciones.setText("AGREGAR EDIFICIOS");
        ABC_Asignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_AsignacionesActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Asignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 660, 290, 40));

        ABC_Edificios2.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Edificios2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Edificios2.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Edificios2.setText("ELIMINAR EDIFICIOS");
        ABC_Edificios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Edificios2ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Edificios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, 290, 40));

        ABC_Edificios1.setBackground(new java.awt.Color(43, 46, 46));
        ABC_Edificios1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        ABC_Edificios1.setForeground(new java.awt.Color(250, 250, 244));
        ABC_Edificios1.setText("AGREGAR EDIFICIOS");
        ABC_Edificios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_Edificios1ActionPerformed(evt);
            }
        });
        getContentPane().add(ABC_Edificios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 290, 40));

        fondo.setBackground(new java.awt.Color(59, 55, 51));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.jpg"))); // NOI18N
        fondo.setText("Fondo General");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InicioColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioColaborador().setVisible(true);
            }
        });
    }
    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        EstructuraGeneral.cerrarSesion();
        this.dispose();
        new Login();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void ABC_Estudiantes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Estudiantes2ActionPerformed
        new EditarEstudiante();
        
    }//GEN-LAST:event_ABC_Estudiantes2ActionPerformed

    private void ABC_Catedraticos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Catedraticos1ActionPerformed
        new AgregarCatedratico();
    }//GEN-LAST:event_ABC_Catedraticos1ActionPerformed

    private void ABC_Estudiantes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Estudiantes3ActionPerformed
        new VisualizarEstudiante();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Estudiantes3ActionPerformed

    private void ABC_Estudiantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Estudiantes1ActionPerformed
        // TODO add your handling code here:
        new AgregarEstudiante();
    }//GEN-LAST:event_ABC_Estudiantes1ActionPerformed

    private void ABC_Catedraticos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Catedraticos4ActionPerformed
        new EditarCatedratico();
    }//GEN-LAST:event_ABC_Catedraticos4ActionPerformed

    private void ABC_Catedraticos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Catedraticos3ActionPerformed
       new VisualizarCatedraticos();
    }//GEN-LAST:event_ABC_Catedraticos3ActionPerformed

    private void ABC_Cursos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Cursos2ActionPerformed
    new EditarCurso();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Cursos2ActionPerformed

    private void ABC_AsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_AsignacionesActionPerformed
        new AgregarEdificio();
    }//GEN-LAST:event_ABC_AsignacionesActionPerformed

    private void ABC_Edificios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Edificios2ActionPerformed
        new EliminarEdificio();
    }//GEN-LAST:event_ABC_Edificios2ActionPerformed

    private void ABC_Estudiantes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Estudiantes4ActionPerformed
        new EditarEstudiante();
    }//GEN-LAST:event_ABC_Estudiantes4ActionPerformed

    private void ABC_Cursos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Cursos1ActionPerformed
        new AgregarCurso();
    }//GEN-LAST:event_ABC_Cursos1ActionPerformed

    private void ABC_Salones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Salones1ActionPerformed
        new AgregarSalon();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Salones1ActionPerformed

    private void ABC_Salones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Salones2ActionPerformed
        new EditarSalon();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Salones2ActionPerformed

    private void ABC_Salones3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Salones3ActionPerformed
        new EditarSalon();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Salones3ActionPerformed

    private void ABC_Cursos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Cursos3ActionPerformed
        new VisualizarCursos();
    }//GEN-LAST:event_ABC_Cursos3ActionPerformed

    private void ABC_Cursos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Cursos4ActionPerformed
        new EditarCurso();
    }//GEN-LAST:event_ABC_Cursos4ActionPerformed

    private void ABC_Catedraticos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Catedraticos2ActionPerformed
        new EditarCatedratico();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Catedraticos2ActionPerformed

    private void ABC_Edificios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_Edificios1ActionPerformed
        new AgregarEdificio();        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_Edificios1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ABC_Asignaciones;
    public javax.swing.JButton ABC_Catedraticos1;
    public javax.swing.JButton ABC_Catedraticos2;
    public javax.swing.JButton ABC_Catedraticos3;
    public javax.swing.JButton ABC_Catedraticos4;
    public javax.swing.JButton ABC_Cursos1;
    public javax.swing.JButton ABC_Cursos2;
    public javax.swing.JButton ABC_Cursos3;
    public javax.swing.JButton ABC_Cursos4;
    public javax.swing.JButton ABC_Edificios1;
    public javax.swing.JButton ABC_Edificios2;
    public javax.swing.JButton ABC_Estudiantes1;
    public javax.swing.JButton ABC_Estudiantes2;
    public javax.swing.JButton ABC_Estudiantes3;
    public javax.swing.JButton ABC_Estudiantes4;
    public javax.swing.JButton ABC_Salones1;
    public javax.swing.JButton ABC_Salones2;
    public javax.swing.JButton ABC_Salones3;
    public javax.swing.JButton cerrarSesion;
    public javax.swing.JLabel datoNombre;
    public javax.swing.JLabel datoUsuario;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel instruccionesUsuario2;
    public javax.swing.JLabel instruccionesUsuario4;
    public javax.swing.JLabel instruccionesUsuario5;
    public javax.swing.JLabel logo;
    public javax.swing.JLabel titulo;
    public javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public javax.swing.JLabel titulo3;
    public javax.swing.JLabel titulo4;
    public javax.swing.JLabel titulo5;
    public javax.swing.JLabel titulo6;
    public javax.swing.JLabel titulo7;
    // End of variables declaration//GEN-END:variables
}
